spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret-key: ${JWT_TOKEN}
  token:
    expired-time-ms: ${TOKEN_EXPIRED_TIME_MS}


project:
  upload:
    path: C:\Users\Playdata\IdeaProjects\ex\demo\src\main\resources\static\images


cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${REGION_STATIC}
      auto: false
    stack:
      auto: false

imp:
  apiKey: ${IMP_KEY}
  secretKey: ${IMP_SECRET}

