server:
  port: 7073

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EURECA_URL}

spring:
  application:
    name: product-image-service
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_URL}

  datasource:
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true


cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${REGION_STATIC}
      auto: false
    stack:
      auto: false

jwt:
  secret-key: ${JWT_TOKEN}
  token:
    expired-time-ms: ${TOKEN_EXPIRED_TIME_MS}