server:
  port: 7010

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EURECA_URL}

spring:
  application:
    name: member-service
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_URL}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret-key: ${JWT_TOKEN}
  access-token-exp-ms: ${TOKEN_EXPIRED_TIME_MS}